In [1]:
import pandas as pd

In [2]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [3]:
dataset = pd.DataFrame(raw_data, columns=['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])

In [4]:
dataset

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

# What is the mean preTestScore from the regiment Nighthawks?

In [24]:
mean_nighthawks = dataset.groupby('regiment')['preTestScore'].mean()
print(mean_nighthawks)
print(mean_nighthawks.to_dict())
print(f"Mean preTestScore of Nighthawks", mean_nighthawks['Nighthawks'])

regiment
Dragoons      15.50
Nighthawks    15.25
Scouts         2.50
Name: preTestScore, dtype: float64
{'Dragoons': 15.5, 'Nighthawks': 15.25, 'Scouts': 2.5}
Mean preTestScore of Nighthawks 15.25

In [23]:
mean_nighthawks = dataset.groupby('regiment')[['preTestScore']].mean()  # 2D Dataframe
mean_nighthawks

            preTestScore
regiment
Dragoons           15.50
Nighthawks         15.25
Scouts              2.50

# Present general statistics by company

In [25]:
dataset['company'].describe()

count      12
unique      2
top       1st
freq        6
Name: company, dtype: object

# What is the mean of each company's preTestScore?

In [26]:
dataset.groupby('company')['preTestScore'].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

# Present the mean preTestScores grouped by regiment and company

In [30]:
reg_and_comp = dataset.groupby(['regiment', 'company'])['preTestScore'].mean().unstack()
reg_and_comp.ndim

2

In [33]:
reg_and_comp = dataset.groupby(['regiment', 'company'])['preTestScore'].mean()
print(reg_and_comp.ndim)
print(reg_and_comp)

1
regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

# Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [32]:
dataset.groupby(['regiment', 'company'], as_index=False)['preTestScore'].mean()

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

# Group the entire dataframe by regiment and company

In [34]:
dataset.groupby(['regiment', 'company'])

# What is the number of observations in each regiment and company

In [50]:
dataset.groupby(['regiment', 'company']).size()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

In [45]:
dataset[['regiment', 'company']].count()

regiment    12
company     12
dtype: int64

# Iterate over a group and print the name and the whole data from the regiment

In [43]:
for name, group in dataset.groupby('regiment'):
    print("Regiment:", name)
    print(group)
    print("-" * 40)

Regiment: Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
----------------------------------------
Regiment: Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
----------------------------------------
Regiment: Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70
----------------------------------------

In [46]:
for (regiment, company), group in dataset.groupby(['regiment', 'company']):
    print("Regiment:", regiment, "| Company:", company)
    print(group)
    print("-" * 40)

Regiment: Dragoons | Company: 1st
   regiment company   name  preTestScore  postTestScore
4  Dragoons     1st  Cooze             3             70
5  Dragoons     1st  Jacon             4             25
----------------------------------------
Regiment: Dragoons | Company: 2nd
   regiment company    name  preTestScore  postTestScore
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
----------------------------------------
Regiment: Nighthawks | Company: 1st
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
----------------------------------------
Regiment: Nighthawks | Company: 2nd
     regiment company    name  preTestScore  postTestScore
2  Nighthawks     2nd     Ali            31             57
3  Nighthawks     2nd  Milner             2             62
----------------------------------------
Regiment: Scouts | Company: 1st
  regiment company   name  preTestScore  postTestScore
8   Scouts     1st  Sloan             2             62
9   Scouts     1st  Piger             3             70
----------------------------------------
Regiment: Scouts | Company: 2nd
   regiment company   name  preTestScore  postTestScore
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70
----------------------------------------